# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 564)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 801, 561))
        font = QtGui.QFont()
        font.setFamily("mononoki Nerd Font")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 781, 491))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 779, 489))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.chat_log = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.chat_log.setGeometry(QtCore.QRect(0, 0, 781, 491))
        self.chat_log.setReadOnly(True)
        self.chat_log.setObjectName("chat_log")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.send_btn = QtWidgets.QPushButton(self.groupBox)
        self.send_btn.setGeometry(QtCore.QRect(570, 510, 71, 41))
        self.send_btn.setObjectName("send_btn")
        self.send_file_btn = QtWidgets.QPushButton(self.groupBox)
        self.send_file_btn.setGeometry(QtCore.QRect(650, 510, 141, 41))
        self.send_file_btn.setObjectName("send_file_btn")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 510, 551, 41))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 549, 39))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.message = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.message.setGeometry(QtCore.QRect(0, 0, 551, 41))
        self.message.setObjectName("message")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea_2.raise_()
        self.scrollArea.raise_()
        self.send_btn.raise_()
        self.send_file_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.send_btn.setText(_translate("MainWindow", "Send"))
        self.send_file_btn.setText(_translate("MainWindow", "Choose File(s)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
