# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(483, 330)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(-20, -60, 511, 411))
        font = QtGui.QFont()
        font.setFamily("mononoki Nerd Font")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(60, 190, 91, 31))
        self.label_2.setObjectName("label_2")
        self.password = QtWidgets.QLineEdit(self.groupBox)
        self.password.setGeometry(QtCore.QRect(170, 180, 291, 41))
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(60, 140, 91, 31))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(220, 80, 101, 31))
        font = QtGui.QFont()
        font.setFamily("mononoki Nerd Font")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.username = QtWidgets.QLineEdit(self.groupBox)
        self.username.setGeometry(QtCore.QRect(170, 130, 291, 41))
        self.username.setObjectName("username")
        self.register_btn = QtWidgets.QPushButton(self.groupBox)
        self.register_btn.setGeometry(QtCore.QRect(210, 340, 111, 31))
        self.register_btn.setObjectName("register_btn")
        self.publickey_file = QtWidgets.QLineEdit(self.groupBox)
        self.publickey_file.setGeometry(QtCore.QRect(170, 280, 191, 41))
        self.publickey_file.setObjectName("publickey_file")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(60, 290, 101, 31))
        self.label_4.setObjectName("label_4")
        self.load_key_btn = QtWidgets.QPushButton(self.groupBox)
        self.load_key_btn.setGeometry(QtCore.QRect(370, 280, 91, 41))
        self.load_key_btn.setObjectName("load_key_btn")
        self.password_again = QtWidgets.QLineEdit(self.groupBox)
        self.password_again.setGeometry(QtCore.QRect(170, 230, 291, 41))
        self.password_again.setObjectName("password_again")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(60, 240, 91, 31))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Password"))
        self.label.setText(_translate("Dialog", "Username"))
        self.label_3.setText(_translate("Dialog", "Register"))
        self.register_btn.setText(_translate("Dialog", "Register"))
        self.label_4.setText(_translate("Dialog", "Public Key"))
        self.load_key_btn.setText(_translate("Dialog", "Load File"))
        self.label_5.setText(_translate("Dialog", "Re-Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
