# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(401, 281)
        self.login_group = QtWidgets.QGroupBox(LoginDialog)
        self.login_group.setGeometry(QtCore.QRect(-20, -10, 491, 311))
        font = QtGui.QFont()
        font.setFamily("mononoki Nerd Font")
        font.setPointSize(12)
        self.login_group.setFont(font)
        self.login_group.setTitle("")
        self.login_group.setObjectName("login_group")
        self.username = QtWidgets.QLineEdit(self.login_group)
        self.username.setGeometry(QtCore.QRect(140, 100, 241, 41))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.login_group)
        self.password.setGeometry(QtCore.QRect(140, 160, 241, 41))
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(self.login_group)
        self.label.setGeometry(QtCore.QRect(50, 100, 91, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.login_group)
        self.label_2.setGeometry(QtCore.QRect(50, 160, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.login_group)
        self.label_3.setGeometry(QtCore.QRect(200, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("mononoki Nerd Font")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.register_btn = QtWidgets.QPushButton(self.login_group)
        self.register_btn.setGeometry(QtCore.QRect(270, 220, 111, 31))
        self.register_btn.setObjectName("register_btn")
        self.login_btn = QtWidgets.QPushButton(self.login_group)
        self.login_btn.setGeometry(QtCore.QRect(140, 220, 91, 31))
        self.login_btn.setObjectName("login_btn")
        self.label_7 = QtWidgets.QLabel(self.login_group)
        self.label_7.setGeometry(QtCore.QRect(240, 220, 31, 31))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Dialog"))
        self.label.setText(_translate("LoginDialog", "Username"))
        self.label_2.setText(_translate("LoginDialog", "Password"))
        self.label_3.setText(_translate("LoginDialog", "Login"))
        self.register_btn.setText(_translate("LoginDialog", "Register"))
        self.login_btn.setText(_translate("LoginDialog", "Login"))
        self.label_7.setText(_translate("LoginDialog", "or"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec_())
